### ISSUE TITLE
Webpack ulanmakdan utananokmy?

### ISSUE THREAD

**Issue by richxcame** [begench02/react-boilerplate#1]
😎

**Comment by begenchgeldyev** [comment]
Ozun bilenok bolyn icin yanaymy? 😆😆😆

**Comment by richxcame** [comment]
Bilyan okunsin wagt yitirenine

**Comment by begenchgeldyev** [comment]
Vite gowulay, yone webpack-am gorayin diydimlay

**Comment by richxcame** [comment]
> Vite gowulay, yone webpack-am gorayin diydimlay

sheydegor). Onda yapayjak `issue`-ny
